#!/bin/bash

test_path=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
(
    flags=""
    [[ "$1" == "--verbose" ]] && flags="--show-output-of-passing-tests"
    cd "$test_path"
    BATS_LIB_PATH="$test_path/tmp/bats" ./tmp/bats/bats-core-1.9.0/bin/bats $flags ./tests.bats
)
