#!/usr/bin/env bash
version=2-dev

script_path=$(dirname "$(readlink -f "$BASH_SOURCE")")

function usage {
    echo "uenv installer"
    echo "Usage: install [--prefix=] [--yes] [--help]"
    echo ""
    echo "--prefix  : the installation path (default \$HOME/.local)"
    echo "--yes     : default response to all queries is yes"
    echo "--help    : print this message"
}

function prompt_bash_update {
    path=$1
    always_yes=$2

    response="yes"
    if [ "$always_yes" != "yes" ]
    then
        # prompt the user
        echo
        read -p "Do you want to update $HOME/.bashrc to load uenv? [y/N] " response

        # default to No if no input
        response=${response:-N}
    fi

    # check the user's response
    case $response in
        [yY][eE][sS]|[yY])
            # if yes, create the directory
            echo "" >> $HOME/.bashrc
            echo "# configure the user-environment (uenv) utility" >> $HOME/.bashrc
            echo "source ${path}/bin/activate-uenv" >> $HOME/.bashrc

            echo
            echo "$HOME/.bashrc has been updated."
            ;;
        *)
            # if anything other than yes, do nothing
            echo
            echo "$HOME/.bashrc is umodified - you can update it yourself:"
            echo "echo \"source ${path}/bin/activate-uenv\" >> $HOME/.bashrc"
            ;;
    esac
}

# set the default installation location
prefix="$HOME/.local"

# get number of arguments
arg_count=$#

# default is to always query user for yes/no prompts
always_yes=no

# loop over all arguments
for (( i=1; i<=$arg_count; i++ ))
do
    arg=${!i}
    case $arg in
        --prefix=*)
        prefix="${arg#*=}"
        ;;
        --yes)
        always_yes=yes
        ;;
        --help)
        usage
        exit 0
        ;;
        *)
        echo "Error: unknown argument $arg"
        echo
        usage
        exit 1
        ;;
    esac
done

echo "installing uenv version $version in $prefix"
echo

mkdir -p $prefix/bin
echo "installing $prefix/bin/activate-uenv"
cp $script_path/activate $prefix/bin/activate-uenv
sed "s|@@prefix@@|$prefix|g" -i $prefix/bin/activate-uenv
sed "s|@@version@@|$version|g" -i $prefix/bin/activate-uenv

mkdir -p $prefix/libexec
echo "installing $prefix/libexec/uenv-impl"
cp $script_path/uenv-impl $prefix/libexec/uenv-impl

prompt_bash_update "$prefix" "$always_yes"
