#!/usr/bin/env bash
version=2

script_path=$(dirname "$(readlink -f "$BASH_SOURCE")")

function usage {
    echo "uenv installer"
    echo "Usage: install [--prefix=] [--yes] [--help]"
    echo ""
    echo "--prefix  : the installation path (default /opt/uenv)"
    echo "--user    : install locally for this user (default prefix \$HOME/.local)"
    echo "--yes     : default response to all queries is yes"
    echo "--help    : print this message"
}

function prompt_bash_update {
    activate_script=$1
    always_yes=$2

    response="yes"
    if [ "$always_yes" != "yes" ]
    then
        # prompt the user
        echo
        read -p "Do you want to update $HOME/.bashrc to load uenv? [y/N] " response

        # default to No if no input
        response=${response:-N}
    fi

    # check the user's response
    case $response in
        [yY][eE][sS]|[yY])
            # if yes, create the directory
            echo "" >> $HOME/.bashrc
            echo "# configure the user-environment (uenv) utility" >> $HOME/.bashrc
            echo "source ${activate_script}" >> $HOME/.bashrc

            echo
            echo "$HOME/.bashrc has been updated."
            ;;
        *)
            # if anything other than yes, do nothing
            echo
            echo "$HOME/.bashrc is umodified - you can update it yourself:"
            echo "echo \"source ${activate_script}\" >> $HOME/.bashrc"
            ;;
    esac
}

# set the default installation location
prefix_local="$HOME/.local"
prefix_system="/opt"

# get number of arguments
arg_count=$#

# default is to always query user for yes/no prompts
always_yes=no

# default install system wide
local_install=no

# loop over all arguments
for (( i=1; i<=$arg_count; i++ ))
do
    arg=${!i}
    case $arg in
        --prefix=*)
        prefix="${arg#*=}"
        ;;
        --local)
        local_install=yes
        ;;
        --yes)
        always_yes=yes
        ;;
        --debug)
        uenv_debug=yes
        ;;
        --help)
        usage
        exit 0
        ;;
        *)
        echo "Error: unknown argument $arg"
        echo
        usage
        exit 1
        ;;
    esac
done

if [ "$local_install" == "yes" ]
then
    prefix="${prefix:-$prefix_local}"
else
    prefix="${prefix:-$prefix_system}/uenv"
fi

[[ "x$uenv_debug" == xyes ]] && show=echo || show=""

echo "installing uenv version $version in $prefix"
echo "local install: $local_install"

$show mkdir -p "$prefix/libexec"
$show chmod 755 "$prefix/libexec"
if [ "$local_install" == "no" ]
then
    $show chmod -R 755 "$prefix"
    init_path="/etc/profile.d/uenv.sh"
else
    $show mkdir -p "$prefix/bin"
    init_path="$prefix/bin/activate-uenv"
fi

impl_path="$prefix/libexec/uenv-impl"
echo "installing $impl_path"
$show cp "$script_path/uenv-impl" "$impl_path"
$show sed "s|@@version@@|$version|g" -i "$impl_path"
$show chmod 755 "$impl_path"

# Copy the initialisation script
echo "installing $init_path"
$show cp "$script_path/activate" "$init_path"
$show sed "s|@@impl@@|$impl_path|g"  -i "$init_path"
$show sed "s|@@prefix@@|$prefix|g"   -i "$init_path"
$show sed "s|@@version@@|$version|g" -i "$init_path"
$show chmod 644 "$init_path"

[[ "$local_install" == "yes" ]] && prompt_bash_update "$prefix" "$always_yes"
