#!/bin/bash

DIR=$(cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)

if [ "$#" -eq 0 ]; then
  install_path="$DIR/../scratch"
else
  install_path="$(realpath $1)"
fi

source $DIR/setup_repos.bash

setup_repos $install_path

cp -R $DIR/../data/env-files $install_path/
cp -R $DIR/../data/config-files $install_path/
