name: artifacts
on: [push, pull_request]

## Tests that all artifacts can be built on every push.
## Uploads the artifacts to the GitHub release page for tags.

jobs:
  rpm:
    runs-on: ubuntu-20.04
    container: registry.suse.com/bci/bci-base:15.5
    steps:
      - name: setup-environment
        run: |
          zypper install -y libmount-devel gcc make rpm-build git sudo python3 wget
      - name: clone
        uses: actions/checkout@v2
      - name: build-srpm
        run: |
          set -x
          ./rpm/generate-rpm.sh -s . -b rpm-build
          rpmbuild -bs --define "_topdir rpm-build" rpm-build/SPECS/uenv.spec
          sudo rpmbuild --rebuild "$(find rpm-build/SRPMS -name '*.rpm' -type f -print -quit)" --define "_topdir $(pwd)/rpm-build"
          sudo rpm --install "$(find rpm-build/RPMS -name '*.rpm' -type f -print -quit)"
          find rpm-build -name '*.rpm' -type f -exec cp {} . \;
      - name: upload-rpm
        uses: actions/upload-artifact@v3
        with:
          name: rpm
          path: '*.rpm'

  tag-release:
    runs-on: ubuntu-20.04
    needs: rpm
    steps:
      - name: download-artifacts
        uses: actions/download-artifact@v3
        with:
          name: rpm
      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: '*.rpm'
