name: builds
on: [push, pull_request]

jobs:
  makefile:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: setup
        run: |
          # create the test environment
          ./test/setup
      - name: test
        run: |
          ./test/test
